

#if !defined(NTH_RENDERER_VK_GLOBAL_FUNCTION)
#define NTH_RENDERER_VK_GLOBAL_FUNCTION( fun )
#endif

#if !defined(NTH_RENDERER_VK_GLOBAL_FUNCTION_OPTIONAL)
#define NTH_RENDERER_VK_GLOBAL_FUNCTION_OPTIONAL( fun )
#endif

NTH_RENDERER_VK_GLOBAL_FUNCTION(vkCreateInstance)
NTH_RENDERER_VK_GLOBAL_FUNCTION(vkEnumerateInstanceExtensionProperties)
NTH_RENDERER_VK_GLOBAL_FUNCTION(vkEnumerateInstanceLayerProperties)
NTH_RENDERER_VK_GLOBAL_FUNCTION_OPTIONAL(vkEnumerateInstanceVersion)

#undef NTH_RENDERER_VK_GLOBAL_FUNCTION
#undef NTH_RENDERER_VK_GLOBAL_FUNCTION_OPTIONAL