name: Linux-Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/checkout@v3

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build targets
        run: xmake build --yes